package br.com.jcomputacao.sped.efd.pisCofins;

import java.text.NumberFormat;

/**
 * Tabela 4.3.7 em http://www1.receita.fazenda.gov.br/sistemas/efd-pis-cofins/tabela-codigos/tabelas-de-codigos.htm
 * 17/11/2011 21:28:06
 * @author Murilo
 */
public enum BaseCalculoCredito {

    AQUISICAO_BENS_REVENDA,
    AQUISICAO_BENS_UTILIZACAO_INSUMO,
    AQUISICAO_SERVICOS_UTILIZACAO_INSUMO,
    ENERGIA_ELETRICA_TERMICA,
    ALUGUEL_PREDIAL,
    ALUGUEL_MAQUINAS_EQUIPAMENTOS,
    ARMAZENAGEM_MERCADORIA_FRETE_NA_VENDA,
    CONTRAPRESTACAO_ARRENDAMENTO_MERCANTIL,
    MAQUINAS_EQUIPAMENTOS_ATIVO_IMOBILIZADO_CREDITO_ENCARGOS_DEPRECIACAO,
    MAQUINAS_EQUIPAMENTOS_ATIVO_IMOBILIZADO_CREDITO_VALOR_AQUISICAO,
    AMORTIZACAO_DEPRECIACAO_EDIFICAO_BENFEITORIAS_IMOVEIS,
    DEVOLUCAO_VENDAS_SUJEITAS_INCIDENCIA_NAO_CUMULATIVA,
    OUTRAS_OPERACOES_DIREITO_CREDITO,
    ATIVIDADE_TRANSPORTE_CARGAS_SUBCONTRATACAO,
    ATIVIDADE_IMOBILIARIA_CUSTO_INCORRIDO_UNIDADE_IMOBILIARIA,
    ATIVIDADE_IMOBILIARIA_CUSTO_ORCADO_UNIDADE_NAO_CONCLUIDA,
    ATIVIDADE_PRESTACAO_SERVICOS_LIMPESA_CONSERVACAO_MANUTENCAO_VALES,
    ESTOQUE_ABERTURA_BENS;
    
    public String getCodigo() {
        NumberFormat ii = NumberFormat.getIntegerInstance();
        ii.setMinimumIntegerDigits(2);
        return ii.format(ordinal()+1);
    }
}
